utils::globalVariables(c("."))

#' Make climate normals for \code{LandR.CS}
#' 
#' Trims and masks the climate normals, in case they aren't the same extent.
#' It assumes climate normal and projected data has already been generated by \code{climateNA}.
#'
#' @param pathToNormalRasters file path of the directory containing climate normal data,
#'                            assumed 1950-1980 and 1980-2010
#' @param pathToFutureRasters the file path of the directory containing the projected climate files
#' @param origTemplate the original DEM used to create the climate files
#' @param outputDir file path to directory where raster stacks will be written
#' @param years years included in the climate data
#' @param writeCMINormal write the CMI normal to disk
#' @param rasterPrefix name of raster file, to be followed by e.g., \file{ATA_2011-2100.grd}.
#'
#' @note  The unit used by the output ATA is the same as the input MAT, i.e., 1/10th of a degree
#'        in \code{climateNA }.
#'
#' @author Ian Eddy
#' @export
#' @importFrom raster crop crs getValues mask raster setValues stack trim writeRaster
#' @importFrom magrittr %>%
#' @importFrom utils tail
#' @rdname makeLandRCS
makeLandRCS <- function(pathToNormalRasters, pathToFutureRasters, rasterPrefix, outputDir,
                        origTemplate, years = 2011:2100, writeCMINormal = FALSE) {
  origTemplate <- trim(origTemplate)
  crs(origTemplate) <- "+init=epsg:4326 +proj=longlat"

  # normalCMI
  # normal MAP
  normalMAPs <- list.files(
    path = pathToNormalRasters, pattern = "MAP.asc$",
    recursive = TRUE, full.names = TRUE
  ) %>%
    lapply(., FUN = raster) %>%
    stack(.)
  crs(normalMAPs) <- "+init=epsg:4326 +proj=longlat"
  normalMAPs <- crop(normalMAPs, y = origTemplate) %>%
    mask(., mask = origTemplate)
  normalMAPVals <- (getValues(normalMAPs[[1]]) + getValues(normalMAPs[[2]])) / 2

  # normal Eref
  normalErefs <- list.files(
    path = pathToNormalRasters, pattern = "Eref.asc$",
    recursive = TRUE, full.names = TRUE
  ) %>%
    lapply(., FUN = raster) %>%
    stack(.)
  crs(normalErefs) <- "+init=epsg:4326 +proj=longlat"
  normalErefs <- crop(normalErefs, y = origTemplate) %>%
    mask(., mask = origTemplate)
  normalErefVals <- (getValues(normalErefs[[1]]) + getValues(normalErefs[[2]])) / 2

  # Make CMI
  normalCMI <- raster(normalMAPs[[1]]) %>%
    setValues(., normalMAPVals - normalErefVals)
  crs(normalCMI) <- "+init=epsg:4326 +proj=longlat"
  names(normalCMI) <- paste0(rasterPrefix, "normalCMI.grd")

  # normalMAT
  normalMATs <- list.files(
    path = pathToNormalRasters, pattern = "MAT.asc$",
    recursive = TRUE, full.names = TRUE
  ) %>%
    lapply(., FUN = raster) %>%
    stack(.)
  normalMATs <- crop(normalMATs, y = origTemplate) %>%
    mask(., mask = origTemplate)
  normalVals <- (getValues(normalMATs[[1]]) + getValues(normalMATs[[2]])) / 2


  # Start with MATrasters

  MATrasters <- list.files(pathToFutureRasters,
    pattern = "MAT.asc",
    recursive = TRUE, full.names = TRUE
  ) %>%
    lapply(., FUN = raster) %>%
    stack(.)
  crs(MATrasters) <- "+init=epsg:4326 +proj=longlat"
  MATrasters <- crop(MATrasters, y = origTemplate) %>%
    mask(., mask = origTemplate)

  names(MATrasters) <- paste0(rasterPrefix, "MAT", years)
  MATrasters <- stack(MATrasters) # some functions is converting to brick

  # ATA rasters
  ATArasters <- lapply(names(MATrasters), FUN = function(mat, normal = normalVals) {
    mat <- MATrasters[[mat]]
    MATvals <- getValues(mat)
    ATA <- (MATvals - normal) # transform for saving as INT2S
    ATA <- setValues(mat, ATA)
    crs(ATA) <- "+init=epsg:4326 +proj=longlat"
    return(ATA)
  })

  ATAstack <- stack(ATArasters)
  names(ATAstack) <- paste0("ATA", years)
  print("completed ATA")
  # MAP
  ppRasters <- list.files(pathToFutureRasters,
    pattern = "MAP.asc",
    recursive = TRUE, full.names = TRUE
  ) %>%
    lapply(., FUN = raster) %>%
    lapply(., FUN = "crop", y = origTemplate) %>%
    lapply(., FUN = "mask", mask = origTemplate)


  # Eref
  ErefRasters <- list.files(pathToFutureRasters,
    pattern = "Eref.asc",
    recursive = TRUE, full.names = TRUE
  ) %>%
    lapply(., FUN = raster) %>%
    lapply(., FUN = "crop", y = origTemplate) %>%
    lapply(., FUN = "mask", mask = origTemplate)

  # Calc CMI
  CMI <- lapply(1:length(ppRasters), FUN = function(year, ppStack = ppRasters, ErefStack = ErefRasters) {
    ppRaster <- ppStack[[year]]
    erefRaster <- ErefStack[[year]]
    CMIvals <- getValues(ppRaster) - getValues(erefRaster)
    CMI <- setValues(ppRaster, CMIvals)
    crs(CMI) <- "+init=epsg:4326 +proj=longlat"
    return(CMI)
  })
  CMIstack <- stack(CMI)
  names(CMIstack) <- paste0("CMI", years)

  writeRaster(ATAstack,
    filename = file.path(outputDir, paste0(
      rasterPrefix, "_ATA", years[1], "-",
      tail(years, 1), ".grd"
    )), datatype = "INT2S"
  )
  writeRaster(CMIstack,
    filename = file.path(outputDir, paste0(
      rasterPrefix, "_CMI", years[1], "-",
      tail(years, 1), ".grd"
    )), datatype = "INT2S"
  )
  if (writeCMINormal) {
    writeRaster(normalCMI,
      filename = file.path(outputDir, paste0(rasterPrefix, "CMInormal.tif"))
    )
  }
}
