utils::globalVariables(c("."))

#' Make climate normals for `LandR.CS`
#'
#' Trims and masks the climate normals, in case they aren't the same extent.
#' It assumes climate normal and projected data has already been generated by `ClimateNA`.
#'
#' @param pathToNormalRasters file path of the directory containing climate normal data,
#'                            assumed 1950-1980 and 1980-2010
#' @param pathToFutureRasters the file path of the directory containing the projected climate files
#' @param origTemplate the original DEM used to create the climate files
#' @param outputDir file path to directory where raster stacks will be written
#' @param years years included in the climate data
#' @param writeCMINormal write the CMI normal to disk
#' @param rasterPrefix name of raster file, to be followed by e.g., \file{ATA_2011-2100.grd}.
#'
#' @return `NULL` invisibly. Invoked for side effect of writing rasters to disk.
#'
#' @author Ian Eddy, Alex Chubaty
#' @export
#' @importFrom terra crop crs mask rast setValues trim values writeRaster
#' @importFrom utils tail
#' @rdname makeLandRCS
makeLandRCS <- function(pathToNormalRasters, pathToFutureRasters, rasterPrefix, outputDir,
                        origTemplate, years = 2011:2100, writeCMINormal = FALSE) {
  browser()
  origTemplate <- trim(origTemplate)

  ## normal MAP
  normalMAPs <- list.files(
    path = pathToNormalRasters, pattern = "MAP.asc$",
    recursive = TRUE, full.names = TRUE
  ) |>
    lapply(FUN = rast) |>
    rast()
  normalMAPs <- crop(normalMAPs, y = origTemplate) |>
    mask(mask = origTemplate)
  normalMAPVals <- (values(normalMAPs[[1]], mat = FALSE) + values(normalMAPs[[2]], mat = FALSE)) / 2

  ## normal Eref
  normalErefs <- list.files(
    path = pathToNormalRasters, pattern = "Eref.asc$",
    recursive = TRUE, full.names = TRUE
  ) |>
    lapply(FUN = rast) |>
    rast()
  normalErefs <- crop(normalErefs, y = origTemplate) |>
    mask(mask = origTemplate)
  normalErefVals <- (values(normalErefs[[1]], mat = FALSE) + values(normalErefs[[2]], mat = FALSE)) / 2

  ## normal CMI
  normalCMI <- rast(normalMAPs[[1]]) |>
    setValues(normalMAPVals - normalErefVals)
  names(normalCMI) <- paste0(rasterPrefix, "normalCMI.grd")

  ## normalMAT
  normalMATs <- list.files(
    path = pathToNormalRasters, pattern = "MAT.asc$",
    recursive = TRUE, full.names = TRUE
  ) |>
    lapply(FUN = rast) |>
    rast()
  normalMATs <- crop(normalMATs, y = origTemplate) |>
    mask(mask = origTemplate)
  normalVals <- (values(normalMATs[[1]], mat = FALSE) + values(normalMATs[[2]], mat = FALSE)) / 2

  ## start with MAT rasters
  MATrasters <- list.files(pathToFutureRasters,
    pattern = "MAT[.]asc",
    recursive = TRUE, full.names = TRUE
  ) |> sort()
  ids <- grep(paste0("_", years, "Y$", collapse = "|"), basename(dirname(MATrasters)))
  MATrasters <- MATrasters[ids] |>
    lapply(FUN = rast) |>
    rast() |>
    crop(MATrasters, y = origTemplate) |>
    mask( mask = origTemplate)

  names(MATrasters) <- paste0(rasterPrefix, "MAT", years)

  ## ATA rasters
  ATArasters <- lapply(names(MATrasters), FUN = function(mat, normal = normalVals) {
    mat <- MATrasters[[mat]]
    MATvals <- values(mat, mat = FALSE)
    ATA <- (MATvals - normal) # transform for saving as INT2S
    ATA <- setValues(mat, ATA)
    return(ATA)
  })
  ATAstack <- rast(ATArasters)
  names(ATAstack) <- paste0("ATA", years)
  print("completed ATA")

  ## MAP
  ppRasters <- list.files(pathToFutureRasters,
    pattern = "MAP.asc",
    recursive = TRUE, full.names = TRUE
  ) |> sort()
  ids <- grep(paste0("_", years, "Y$", collapse = "|"), basename(dirname(ppRasters)))
  ppRasters <- ppRasters[ids] |>
    lapply(FUN = rast) |>
    lapply(FUN = "crop", y = origTemplate) |>
    lapply(FUN = "mask", mask = origTemplate)

  ## Eref
  ErefRasters <- list.files(pathToFutureRasters,
    pattern = "Eref.asc",
    recursive = TRUE, full.names = TRUE
  ) |> sort()
  ids <- grep(paste0("_", years, "Y$", collapse = "|"), basename(dirname(ErefRasters)))
  ErefRasters <- ErefRasters[ids] |>
    lapply(FUN = rast) |>
    lapply(FUN = "crop", y = origTemplate) |>
    lapply(FUN = "mask", mask = origTemplate)

  ## calc CMI
  CMI <- lapply(1:length(ppRasters), FUN = function(year, ppStack = ppRasters, ErefStack = ErefRasters) {
    ppRaster <- ppStack[[year]]
    erefRaster <- ErefStack[[year]]
    CMIvals <- values(ppRaster, mat = FALSE) - values(erefRaster, mat = FALSE)
    CMI <- setValues(ppRaster, CMIvals)
    return(CMI)
  })
  CMIstack <- rast(CMI)
  names(CMIstack) <- paste0("CMI", years)

  writeRaster(ATAstack,
    filename = file.path(outputDir, paste0(
      rasterPrefix, "_ATA", years[1], "-",
      tail(years, 1), ".grd"
    )), datatype = "INT2S"
  )

  writeRaster(CMIstack,
    filename = file.path(outputDir, paste0(
      rasterPrefix, "_CMI", years[1], "-",
      tail(years, 1), ".grd"
    )), datatype = "INT2S"
  )

  if (writeCMINormal) {
    writeRaster(normalCMI,
      filename = file.path(outputDir, paste0(rasterPrefix, "CMInormal.tif"))
    )
  }

  return(invisible(NULL))
}
